/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calcu;

import com.sun.xml.internal.ws.util.StringUtils;

/**
 *
 * @author ASUS
 */

public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        result = new javax.swing.JLabel();
        b0 = new javax.swing.JButton();
        jequ = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bmult = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bminus = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bplus = new javax.swing.JButton();
        bpoint = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(255, 0, 51));
        setLocation(new java.awt.Point(700, 250));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        result.setBackground(new java.awt.Color(255, 255, 255));
        result.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));
        result.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        result.setText("0");
        result.setAlignmentX(300.0F);
        result.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        result.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 22, 319, 81));

        b0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 413, 60, 60));

        jequ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jequ.setText("=");
        jequ.setPreferredSize(new java.awt.Dimension(50, 50));
        jequ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jequActionPerformed(evt);
            }
        });
        jPanel1.add(jequ, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 413, 60, 60));

        bclear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bclear.setText("C");
        bclear.setPreferredSize(new java.awt.Dimension(50, 50));
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        jPanel1.add(bclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 130, 60, 60));

        bdiv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bdiv.setText("/");
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });
        jPanel1.add(bdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 197, 59, 59));

        b7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 189, 60, 60));

        b8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 189, 60, 60));

        b9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 189, 60, 60));

        bmult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bmult.setText("*");
        bmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmultActionPerformed(evt);
            }
        });
        jPanel1.add(bmult, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 270, 63, 54));

        b4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 267, 60, 60));

        b5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 267, 60, 60));

        b6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 267, 60, 60));

        bminus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bminus.setText("-");
        bminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bminusActionPerformed(evt);
            }
        });
        jPanel1.add(bminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 340, 60, 60));

        b1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 340, 60, 60));

        b2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 340, 60, 60));

        b3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 340, 60, 60));

        bplus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bplus.setText("+");
        bplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bplusActionPerformed(evt);
            }
        });
        jPanel1.add(bplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 413, 60, 60));

        bpoint.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bpoint.setText(".");
        bpoint.setPreferredSize(new java.awt.Dimension(50, 50));
        bpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpointActionPerformed(evt);
            }
        });
        jPanel1.add(bpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 413, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
       if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+="8";
          
           result.setText(n11);
       }
       else
       {
            n22+="8";
          
           result.setText(n22);
       }
        
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
       if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+="9";
          
           result.setText(n11);
       }
       else
       {
            n22+="9";
          
           result.setText(n22);
       }
    }//GEN-LAST:event_b9ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
       if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+="1";
          
           result.setText(n11);
       }
       else
       {
            n22+="1";
          
           result.setText(n22);
       }
    }//GEN-LAST:event_b1ActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
        // TODO add your handling code here:
        d=1;
    }//GEN-LAST:event_bdivActionPerformed

    private void bmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmultActionPerformed
        // TODO add your handling code here:
        mul=1;
    }//GEN-LAST:event_bmultActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        // TODO add your handling code here:
        sum=0;
        n1=0;
        n2=0;
        nd1=0;
        nd2=0;
        p=0;
        m=0;
        mul=0;
        d=0;
        point=0;
        n11="";
        n22="";
        result.setText("0");
    }//GEN-LAST:event_bclearActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+="2";
          
           result.setText(n11);
       }
       else
       {
            n22+="2";
          
           result.setText(n22);
       }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+="3";
          
           result.setText(n11);
       }
       else
       {
            n22+="3";
          
           result.setText(n22);
       }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+="4";
          
           result.setText(n11);
       }
       else
       {
            n22+="4";
          
           result.setText(n22);
       }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
       if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+="5";
          
           result.setText(n11);
       }
       else
       {
            n22+="5";
          
           result.setText(n22);
       }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+="6";
           result.setText(n11);
       }
       else
       {
            n22+="6";
          
           result.setText(n22);
       }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+="7";
          
           result.setText(n11);
       }
       else
       {
            n22+="7";
          
           result.setText(n22);
       }
    }//GEN-LAST:event_b7ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+="0";
          
           result.setText(n11);
       }
       else
       {
            n22+="0";
          
           result.setText(n22);
       }
    }//GEN-LAST:event_b0ActionPerformed

    private void jequActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jequActionPerformed
        // TODO add your handling code here:
        if(point==0)
        {
        n1=Integer.parseInt(n11);
        n2=Integer.parseInt(n22);
        if(p==1)
        {
            sum=n1+n2;
            result.setText(sum+"");
        }
        else if(m==1)
        {
            sum=(n1-n2);
            result.setText(sum+"");
        }
        else if(mul==1)
        {
            sum=n1*n2;
            result.setText(sum+"");
        }
        else if(d==1)
        {
            if(n2==0)
            {
                result.setText("Math error!");
            }
            else
            {
              double sm;
            if(n1%n2==0)
            {
                sum=n1/n2;
                result.setText(sum+"");
            }
            else
            {sm=n1/n2;
            result.setText(sm+"");
            }
            }
        }
        }
        else
        {
            //str1 = Double.parseDouble(str);
            nd1=Double.parseDouble(n11);
            nd2=Double.parseDouble(n22);
        if(p==1)
        {
            s=nd1+nd2;
            result.setText(s+"");
        }
        else if(m==1)
        {
            s=(nd1-nd2);
            result.setText(s+"");
        }
        else if(mul==1)
        {
            s=nd1*nd2;
            result.setText(s+"");
        }
        else if(d==1)
        {
            if(nd2==0)
            {
                result.setText("Math error!");
            }
            else
            {
            s=nd1/nd2;
            result.setText(s+"");
            }
        }
        }
    }//GEN-LAST:event_jequActionPerformed

    private void bplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bplusActionPerformed
        // TODO add your handling code here:
        p=1;
    }//GEN-LAST:event_bplusActionPerformed

    private void bminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bminusActionPerformed
        // TODO add your handling code here:
        m=1;
    }//GEN-LAST:event_bminusActionPerformed

    private void bpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpointActionPerformed
        // TODO add your handling code here:
        point=1;
        if(p==0&&m==0&&mul==0&&d==0)
       {
           n11+=".";
          
           result.setText(n11);
       }
       else
       {
            n22+=".";
          
           result.setText(n22);
       }
    }//GEN-LAST:event_bpointActionPerformed

    
    int sum=0,n1=0,n2=0,p=0,m=0,mul=0,d=0;
    double point=0,s=0,nd1=0,nd2=0;
    String n11="",n22="";
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bminus;
    private javax.swing.JButton bmult;
    private javax.swing.JButton bplus;
    private javax.swing.JButton bpoint;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jequ;
    private javax.swing.JLabel result;
    // End of variables declaration//GEN-END:variables
}
